# Generated by Django 4.2.6 on 2024-03-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp1', '0002_otptoken_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='cef5cc', max_length=6),
        ),
    ]
