# Generated by Django 5.0.2 on 2024-03-15 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp1', '0004_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otptoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='OtpToken',
        ),
    ]
