# Generated by Django 5.0.2 on 2024-04-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp1', '0005_remove_otptoken_user_delete_customuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pincode',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
