# Generated by Django 5.0.4 on 2024-05-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp1', '0006_userprofile_address_userprofile_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
