# Generated by Django 5.0.4 on 2024-05-30 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp1', '0008_emaildevice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaildevice',
            old_name='otp',
            new_name='token',
        ),
        migrations.AddField(
            model_name='emaildevice',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emaildevice',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_device', to=settings.AUTH_USER_MODEL),
        ),
    ]
