# Generated by Django 5.0.4 on 2024-05-30 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp1', '0009_rename_otp_emaildevice_token_emaildevice_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaildevice',
            old_name='token',
            new_name='otp',
        ),
        migrations.RemoveField(
            model_name='emaildevice',
            name='email',
        ),
        migrations.AlterField(
            model_name='emaildevice',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp_email_device', to=settings.AUTH_USER_MODEL),
        ),
    ]
