# Generated by Django 5.0.2 on 2024-03-16 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0002_category_image_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('is_listed', models.BooleanField(default=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Image 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Image 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Image 3')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('landing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminn.category')),
            ],
        ),
    ]
