# Generated by Django 5.0.2 on 2024-03-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_listed', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
