# Generated by Django 5.0.4 on 2024-05-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0006_brand_offer_category_offer_product_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='offer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
