# Generated by Django 5.0.4 on 2024-05-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_coupon_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
