# Generated by Django 5.0.4 on 2024-05-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_coupon_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
