# Generated by Django 5.0.4 on 2024-05-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_remove_coupon_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='active',
        ),
        migrations.AddField(
            model_name='coupon',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
