# Generated by Django 5.0.4 on 2024-05-21 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_remove_coupon_active_coupon_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount',
        ),
    ]
