# Generated by Django 5.0.2 on 2024-04-14 06:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0005_product_brand'),
        ('userapp1', '0006_userprofile_address_userprofile_pincode'),
        ('userprofile', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('address', models.TextField()),
                ('payment', models.CharField(max_length=20)),
                ('delivery_status', models.CharField(max_length=20)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('estimate_delivery_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='adminn.product')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='userapp1.userprofile')),
            ],
        ),
    ]
