# Generated by Django 5.0.2 on 2024-04-14 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_alter_order_address_alter_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='estimate_delivery_date',
        ),
    ]
