# Generated by Django 5.0.2 on 2024-04-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0005_product_brand'),
        ('userprofile', '0006_remove_order_estimate_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='adminn.product'),
        ),
    ]
